sampled_data_amount=[944 1215 1183; 1194 1408 1415; 1436 1637 1654; 1539 1887 1708; 1783 1907 1847; 1861 1941 1993];

x=[10:10:60];

pic = bar(x,sampled_data_amount,'grouped');

set(pic, {'facecolor'}, {'g'; 'b'; 'r'})

grid on;

axis([5 65 800 2000]);

set(gca, 'XTick',[10 20 30 40 50 60 70])

set(gca, 'YTick',[800 1100 1400 1700 2000])

set(gca, 'XTickLabel',{'64','81','100','121','144','169'})

set(gca, 'YTickLabel',{'800', '1100', '1400', '1700', '2000'})

xlabel('Number of nodes','FontSize',18)

ylabel('Number of received packets', 'FontSize',18);
set(gca,'fontsize',14);

h = legend('Combine','Prune','Random',2);

set(h,'FontSize',14);

axis square;
